{{- if not .Values.cluster.enableSuperuserAccess }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.superuserSecret.name }}
type: Opaque
data:
  username: {{ .Values.cluster.superuserSecret.username | b64enc | quote }}
  password: {{ .Values.cluster.superuserSecret.password | b64enc | quote }}
{{- end}}