{{- if .Values.cluster.enableSuperuserAccess }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.superuserSecret.name }}
data:
  username: {{ .Values.cluster.superuserSecret.username | b64enc }}
  password: {{ .Values.cluster.superuserSecret.password | b64enc }}
{{- end }}