nameOverride: ""
fullnameOverride: ""

type: postgresql
mode: standalone

recovery:
  method: backup

  pitrTarget:
    time: ""

  backupName: ""
  clusterName: ""
  endpointURL: ""

  endpointCA:
    create: false
    name: ""
    key: ""
    value: ""

  destinationPath: ""
  provider: s3

  s3:
    region: ""
    bucket: ""
    path: "/"
    accessKey: ""
    secretKey: ""

  azure:
    path: "/"
    connectionString: ""
    storageAccount: ""
    storageKey: ""
    storageSasToken: ""
    containerName: ""
    serviceName: blob
    inheritFromAzureAD: false

  google:
    path: "/"
    bucket: ""
    gkeEnvironment: false
    applicationCredentials: ""

  secret:
    create: true
    name: ""

  pgBaseBackup:
    database: app
    secret: ""
    owner: ""
    source:
      host: ""
      port: 5432
      username: ""
      database: "app"
      sslMode: "verify-full"
      passwordSecret:
        create: false
        name: ""
        key: "password"
        value: ""
      sslKeySecret:
        name: ""
        key: ""
      sslCertSecret:
        name: ""
        key: ""
      sslRootCertSecret:
        name: ""
        key: ""

cluster:
  instances: 3
  imageName: ""
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []

  storage:
    size: 8Gi
    storageClass: ""

  walStorage:
    size: 1Gi
    storageClass: ""

  postgresUID: 26
  postgresGID: 26

  resources: {}
  priorityClassName: ""
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  logLevel: "info"
  
  affinity:
    topologyKey: topology.kubernetes.io/zone

  certificates: {}

  enableSuperuserAccess: true
  superuserSecret: ""

  roles: []

  monitoring:
    enabled: false
    podMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      excludeRules: []
    customQueries: []

  postgresql: {}

  initdb: {}

  additionalLabels: {}
  annotations: {}

backups:
  enabled: false
  endpointURL: ""

  endpointCA:
    create: false
    name: ""
    key: ""
    value: ""

  destinationPath: ""
  provider: s3

  s3:
    region: ""
    bucket: ""
    path: "/"
    accessKey: ""
    secretKey: ""

  azure:
    path: "/"
    connectionString: ""
    storageAccount: ""
    storageKey: ""
    storageSasToken: ""
    containerName: ""
    serviceName: blob
    inheritFromAzureAD: false

  google:
    path: "/"
    bucket: ""
    gkeEnvironment: false
    applicationCredentials: ""

  secret:
    create: true
    name: ""

  wal:
    compression: gzip
    encryption: AES256
    maxParallel: 1

  data:
    compression: gzip
    encryption: AES256
    jobs: 2

  scheduledBackups:
    - name: daily-backup
      schedule: "0 0 0 * * *"
      backupOwnerReference: self
      method: barmanObjectStore

  retentionPolicy: "30d"

pooler:
  enabled: false
  type: rw
  poolMode: transaction
  instances: 3

  parameters:
    max_client_conn: "1000"
    default_pool_size: "25"

  monitoring:
    enabled: false
    podMonitor:
      enabled: true

  template: {}
